name: Build Gems hb
on:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  build-platform-gems:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        rubyPlatform: ["aarch64-linux", "x86_64-linux", "arm64-darwin", "x86_64-darwin", "x86_64-linux-musl", "aarch64-linux-musl"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          cargo-vendor: true
          working-directory: ./temporalio
          cache-version: v1-${{ matrix.rubyPlatform }}

      - name: Install musl-tools (for Alpine builds)
        if: contains(matrix.rubyPlatform, 'musl')
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Cross compile gem
        uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.rubyPlatform }}
          ruby-versions: "3.2,3.3,3.4"
          working-directory: ./temporalio

      - name: Upload gem
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.rubyPlatform }}-gem
          path: "temporalio/pkg/*.gem"

  build-source-gem:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Ruby and Rust
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "3.4"
          bundler-cache: true
          cargo-cache: true
          cache-version: v1-source

      - name: Install bundle
        working-directory: ./temporalio
        run: bundle install

      - name: Build
        working-directory: ./temporalio
        run: bundle exec rake build

      - name: Upload gem
        uses: actions/upload-artifact@v4
        with:
          name: source-gem
          path: temporalio/pkg/*.gem

  smoke-test-gems:
    needs:
      - build-platform-gems
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-intel, macos-latest]
        rubyVersion: ["3.2", "3.3", "3.4"]
        include:
          - os: ubuntu-latest
            rubyPlatform: x86_64-linux
          - os: ubuntu-latest
            rubyPlatform: x86_64-linux-musl
          - os: macos-intel
            runsOn: macos-13
            rubyPlatform: x86_64-darwin
          - os: macos-latest
            rubyPlatform: arm64-darwin
    runs-on: ${{ matrix.runsOn || matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download gem
        uses: actions/download-artifact@v4
        with:
          name: ${{ matrix.rubyPlatform }}-gem
          path: local-gem

      - name: Setup Ruby
        uses: oxidize-rb/actions/setup-ruby-and-rust@v1
        with:
          ruby-version: "${{ matrix.rubyVersion }}"
          bundler-cache: true
          cargo-cache: false

      - name: Run smoke test
        run: ruby ./temporalio/smoke_test/smoke_test_gem.rb 'local-gem/*-${{ matrix.rubyPlatform }}.gem'
